
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <div className="min-h-screen bg-background">
            <header className="sticky top-0 z-10 w-full bg-background border-b">
              <div className="container mx-auto px-4 py-4">
                <h1 className="text-2xl font-bold">Resume Builder</h1>
              </div>
            </header>
            <main className="container mx-auto px-4 py-8">{children}</main>
          </div>
            </body>
    </html>
  );
}
