
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import puppeteer from "puppeteer";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

async function downloadPdf() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto("http://localhost:3000/pdf");
  await page.pdf({ path: "resume.pdf", format: "A4" });

  await browser.close();

}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <div className="min-h-screen bg-background">
            <header className="sticky top-0 z-10 w-full bg-background border-b">
              <div className="container mx-auto px-4 py-4">
                <h1 className="text-2xl font-bold text-center">Resume Builder</h1>
              </div>
            </header>
            <main className="mx-auto px-4 py-4">{children}</main>
          </div>
            </body>
    </html>
  );
}
